config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root "articles#index"

  resources :articles do
    resources :comments
  end

  resources :sessions
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :passwords, only: [:create, :new, :edit, :update], param: :password_reset_token

  put "account", to: "registrations#update"
  get "account", to: "registrations#edit"
  delete "account", to: "registrations#destroy"
  post "sign_up", to: "registrations#create"
  get "sign_up", to: "registrations#new"

end

app/views/shared/_flash.html.erb
<! Use INSPECT to see the value of the variable, it comes in handy when you're debugging >
<% if flash[:notice] %>
    <div class="alert alert-info mt-4 role" role="alert">
        <%= flash.now[:notice]%>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash.now[:alert]%>
    </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light bg-body-tertiary navbar", data-bs-theme="light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%=root_path%>">
      <%# <%= image_tag "logo.png", alt:"Logo", width:"30", height:"24", class:"d-inline-block align-text-top"%>
      <img src= <%= asset_path('logo.png') %> alt="Logo" height="44" class="d-inline-block align-text-top">
      Blogs
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=root_path%>">Home</a>
        </li>
        <li class="nav-item navbar-nav me-right mb-2 mb-lg-0">
          <a class="nav-link active" aria-current="page" href="<%=login_path%>">Login</a>
        </li>
        <li class="nav-item navbar-nav me-right mb-2 mb-lg-0">
          <a class="nav-link active" aria-current="page" href="<%=sign_up_path%>">Signup</a>
        </li>
        <%# <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>
        <li class="nav-item">
          <a class="nav-link disabled">Hiring</a>
        </li>
      </ul>
      <ul class="navbar-nav me-right mb-2 mb-lg-0">
        Hi <%= @user&.email %>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>